
import os
from datetime import datetime
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_BREAK

def create_technical_document():
    document = Document()

    # --- Styles ---
    # (Simple style setup)
    style = document.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)

    heading_style = document.styles['Heading 1']
    heading_style.font.name = 'Calibri Light'
    heading_style.font.size = Pt(24)
    heading_style.font.color.rgb = RGBColor(41, 98, 255) # Blue like the theme

    h2_style = document.styles['Heading 2']
    h2_style.font.name = 'Calibri Light'
    h2_style.font.size = Pt(18)
    h2_style.font.color.rgb = RGBColor(0, 150, 136) # Teal

    # --- Title Page ---
    document.add_heading('NeuroStock', 0)
    document.add_heading('NSE Stock Trend Predictor AI', 1)
    
    p = document.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.add_run('\n\n\nTechnical Design & Specification Document').bold = True
    p.add_run(f'\n\nGenerated on: {datetime.now().strftime("%Y-%m-%d")}')
    p.add_run('\n\n\n\nConfidential - Internal Use Only')
    
    document.add_page_break()

    # --- Introduction ---
    document.add_heading('1. Executive Summary', level=1)
    document.add_paragraph(
        "NeuroStock (NSE Stock Trend Predictor AI) is a sophisticated full-stack financial technology application designed to "
        "forecast stock prices for companies listed on the National Stock Exchange (NSE) of India. "
        "The system leverages a hybrid machine learning architecture creating a balance between high-accuracy short-term "
        "predictions and speculative long-term forecasting. It integrates advanced concepts like Technical Indicator Analysis, "
        "Sentiment Analysis using Natural Language Processing (NLP), and Generative AI for qualitative financial insights."
    )

    # --- System Architecture ---
    document.add_heading('2. System Architecture', level=1)
    document.add_paragraph(
        "The application follows a modern decoupled Client-Server architecture."
    )
    
    document.add_heading('2.1 Backend (Python/Flask)', level=2)
    p = document.add_paragraph()
    p.add_run("Framework: ").bold = True
    p.add_run("Flask (Python 3.x)\n")
    p.add_run("ML Core: ").bold = True
    p.add_run("TensorFlow (Keras), Scikit-learn, XGBoost\n")
    p.add_run("Data Source: ").bold = True
    p.add_run("yfinance (Real-time and Historical OHLCV data)\n")
    p.add_run("AI Integration: ").bold = True
    p.add_run("Local LLM Inference via LM Studio (OpenAI-compatible API)")

    document.add_heading('2.2 Frontend (React)', level=2)
    p = document.add_paragraph()
    p.add_run("Framework: ").bold = True
    p.add_run("React 18\n")
    p.add_run("Visualization: ").bold = True
    p.add_run("Lightweight Charts (TradingView) for canvas-based high-performance financial plotting.\n")
    p.add_run("Authentication: ").bold = True
    p.add_run("Firebase Authentication (Email/Password flows)\n")
    p.add_run("State Management: ").bold = True
    p.add_run("React Hooks & Axios for API consumption.")

    # --- 9 Tab Features ---
    document.add_heading('3. Feature Modules (The 9 Tabs)', level=1)
    document.add_paragraph(
        "The user interface is organized into 9 distinct functional tabs, each serving a specific persona or analytical need."
    )

    # 1. Market Tab
    document.add_heading('3.1 Market Dashboard', level=2)
    document.add_paragraph(
        "The default landing view providing a real-time pulse of the market."
    )
    document.add_paragraph(
        "• Features: Ticker Tape displaying continuous price updates, and a responsive Stock Grid.\n"
        "• Filtering: Users can filter stocks by sector (IT, Financials, Auto, Energy, etc.) matching the Nifty 50 constituents.\n"
        "• Interactions: Clicking a stock card opens a detailed view with key metrics."
    )

    # 2. Invest Engine
    document.add_heading('3.2 AI Investment Engine', level=2)
    document.add_paragraph(
        "A simulation engine designed for portfolio planning and automated stock picking."
    )
    document.add_paragraph(
        "• Input: Principal Amount (INR) and target Withdrawal Date.\n"
        "• Process: The engine iterates through the top 30 NSE stocks in real-time, running them through a lightweight version of the prediction models.\n"
        "• Output: Generates a 'Top 3 Investment Picks' report, calculating estimated profit percentages, volatility/stability scores, and an 'AI Advice' summary generated by the LLM explaining the rationale."
    )

    # 3. Prediction (Home)
    document.add_heading('3.3 Prediction & Analysis (Home)', level=2)
    document.add_paragraph(
        "The core functionality for single-stock deep analysis."
    )
    document.add_paragraph(
        "• Controls: Select Stock (Searchable), Choice of Algorithm (LSTM, XGBoost, Random Forest, SVR, etc.), and Future Date.\n"
        "• Visualization: Renders an interactive chart showing the last 100 days of historical data and the forecasted trend line up to the future date.\n"
        "• Context: Displays the predicted closing price and color-codes it (Green/Red) based on growth vs. current price."
    )

    # 4. Comparison
    document.add_heading('3.4 Model Comparison', level=2)
    document.add_paragraph(
        "A/B testing tool for users to validate model confidence."
    )
    document.add_paragraph(
        "• Functionality: Allows users to run two different algorithms (e.g., LSTM vs. XGBoost) simultaneously on the same stock and date.\n"
        "• Utility: Helps users identify consensus between models or spot outliers, improving decision confidence."
    )

    # 5. Portfolio
    document.add_heading('3.5 Portfolio Projector', level=2)
    document.add_paragraph(
        "A calculator for projecting the future value of a specific holding."
    )
    document.add_paragraph(
        "• Input: Stock Name, Current Investment Volume/Value, and Target Date.\n"
        "• Logic: Uses the chosen ML model to predict the price on the target date and extrapolates the percentage gain/loss to the user's specific portfolio size."
    )

    # 6. Positions
    document.add_heading('3.6 Positions Dashboard', level=2)
    document.add_paragraph(
        "An overview of daily market movers within the Nifty 50 ecosystem."
    )
    document.add_paragraph(
        "• Leaderboard: Displays a ranked table of Top Gainers and Losers.\n"
        "• Data Points: Open, Previous Close, Current Price, and Percentage Change.\n"
        "• Sorting: Interactive columns allowing users to sort by name, price, or gain %."
    )

    # 7. 52 Week
    document.add_heading('3.7 52-Week Analysis', level=2)
    document.add_paragraph(
        "A specialized view focusing on long-term momentum and support/resistance levels."
    )
    document.add_paragraph(
        "• Visualization: Plots the current price context against the 52-week High and Low.\n"
        "• Insight: Crucial for determining if a stock is overbought (near high) or oversold (near low)."
    )

    # 8. Sentiment
    document.add_heading('3.8 Market Sentiment', level=2)
    document.add_paragraph(
        "A qualitative analysis module using Natural Language Processing."
    )
    document.add_paragraph(
        "• News Aggregation: Fetches real-time news headlines for the selected stock.\n"
        "• Analysis: The backend (and potentially LLM) scores the news from 0 (Extremely Bearish) to 100 (Extremely Bullish).\n"
        "• Display: Shows a 'Fear & Greed' style gauge and a summary of the news impact."
    )

    # 9. Education
    document.add_heading('3.9 Financial Teacher (FinTeach)', level=2)
    document.add_paragraph(
        "An isolated educational chatbot persona."
    )
    document.add_paragraph(
        "• Difference: Unlike the main AI assistant which focuses on live data, FinTeach is prompted to explain concepts (e.g., 'What is RSI?', 'How does inflation affect stocks?') without Hallucinating live prices.\n"
        "• Interface: Chat-style interface with suggested starter questions."
    )

    # --- Technical Specs & AI ---
    document.add_heading('4. Detailed Technical Specifications', level=1)
    
    document.add_heading('4.1 Machine Learning Models', level=2)
    document.add_paragraph("The system employs an ensemble of models:")
    p = document.add_paragraph()
    p.add_run("1. LSTM (Long Short-Term Memory): ").bold = True
    p.add_run("Deep learning RNN optimal for time-series sequence prediction.\n")
    p.add_run("2. XGBoost & Random Forest: ").bold = True
    p.add_run("Tree-based ensemble methods excellent for capturing non-linear feature relationships.\n")
    p.add_run("3. SVR & Linear Regression: ").bold = True
    p.add_run("Statistical baselines for trend confirmation.")

    document.add_heading('4.2 Generative AI Integration', level=2)
    document.add_paragraph(
        "The project utilizes a Local Inference Server (LM Studio) to run open-weights models like Llama-3 or Gemma locally. "
        "This ensures data privacy and zero API costs. The Flask backend communicates with LM Studio via a compatible REST API to:"
    )
    document.add_paragraph(
        "- Interpret complex technical indicators (RSI, SMA) into plain English.\n"
        "- Summarize news sentiment.\n"
        "- Act as an interactive financial assistant."
    )

    # --- Conclusion ---
    document.add_heading('5. Conclusion', level=1)
    document.add_paragraph(
        "NeuroStock represents a convergence of traditional quantitative finance and modern Generative AI. "
        "By providing not just predicted numbers but also qualitative context (News, Education, AI Explanations), "
        "it serves as a holistic platform for both novice and experienced traders on the NSE market."
    )

    # Save
    file_path = 'NeuroStock_Technical_Technical_Document.docx'
    document.save(file_path)
    print(f"Document saved to {os.path.abspath(file_path)}")

if __name__ == "__main__":
    try:
        create_technical_document()
    except Exception as e:
        print(f"Error: {e}")
